import { v4 as uuidv4 } from 'https://jspm.dev/uuid';

export const menuObj = {
    pizza: [
        {
            uuid: uuidv4(),
            name: "Meat Pizza",
            ingredients: ["beef", "sausage", "bacon", "mozzarella", "marinara"],
            price: 21.99,
            picture: "/images/pizza/meat.jpg",
            vegetarian: false,
            isOrdered: false,
        },
        {
            uuid: uuidv4(),
            name: "Hawaiian Pizza",
            ingredients: ["ham", "pineapple", "mozarella", "marinara"],
            price: 18.99,
            picture: "/images/pizza/hawaiian.jpg",
            vegetarian: false,
            isOrdered: false,
        },
        {
            uuid: uuidv4(),
            name: "Paneer Tandoori Pizza",
            ingredients: ["cilantro", "paneer", "mozarella", "marinara"],
            price: 23.99,
            picture: "/images/pizza/paneer.jpg",
            vegetarian: true,
            isOrdered: false,
        },
    ],
    hamburger: [
        {
            uuid: uuidv4(),
            name: "Smoked Bacon Burger",
            ingredients: ["angus beef", "cheddar Cheese", "brisket", "bacon", "pickles"],
            price: 18.99,
            picture: "/images/burger/bacon.jpg",
            vegetarian: false,
            isOrdered: false,
        },
        {
            uuid: uuidv4(),
            name: "Classic Chicken Sandwich",
            ingredients: ["chicken breast", "lettuce", "tomatoes", "red onions", "mayo"],
            price: 15.99,
            picture: "/images/burger/chicken.jpg",
            vegetarian: false,
            isOrdered: false,
        },
        {
            uuid: uuidv4(),
            name: "Garlic Mushroom Burger",
            ingredients: ["garlic", "mushrooms", "lettuce", "tomato", "onions"],
            price: 19.99,
            picture: "/images/burger/mushroom.jpg",
            vegetarian: true,
            isOrdered: false,
        },
    ],
    beer: [
        {
            uuid: uuidv4(),
            name: "Brown Ale",
            ingredients: ["solstice mild", "dark shocolate", "pale cholate", "brown malt"],
            price: 14.99,
            picture: "/images/beer/brown-ale.jpg",
            nonAlcoholic: false,
            isOrdered: false,
        },
        {
            uuid: uuidv4(),
            name: "Crafted Lager",
            ingredients: ["solstice pilsner", "solstice flaked corn", "dextrapils"],
            price: 13.99,
            picture: "/images/beer/crafted-lager.jpg",
            nonAlcoholic: false,
            isOrdered: false,
        },
        {
            uuid: uuidv4(),
            name: "Solo Pilsner",
            ingredients: ["malted barley", "wheat", "hops", "yeast", "water"],
            price: 15.99,
            picture: "/images/beer/solo-pilsner.jpg",
            nonAlcoholic: true,
            isOrdered: false,
        },
    ],
};