export const menuObj = {
    pizza: [
        {
            uuid: 0,
            name: "Meat Pizza",
            ingredients: ["ham", "pepperoni", "sausage", "bacon", "mozzarella", "marinara"],
            price: 21.99,
            picture: "🍕",
            vegetarian: false,
        },
        {
            uuid: 1,
            name: "Hawaiian Pizza",
            ingredients: ["ham", "pineapple", "mozarella", "marinara"],
            price: 18.99,
            picture: "🍕",
            vegetarian: false,
        },
        {
            uuid: 2,
            name: "Paneer Tandoori Pizza",
            ingredients: ["cilantro", "paneer", "mozarella", "marinara"],
            price: 23.99,
            picture: "🍕",
            vegetarian: true,
        },
    ],
    hamburger: [
        {
            uuid: 0,
            name: "Smoked Bacon Burger",
            ingredients: ["angus beef", "cheddar Cheese", "brisket", "bacon", "pickles"],
            price: 18.99,
            picture: "🍔",
            vegetarian: false,
        },
        {
            uuid: 1,
            name: "Classic Chicken Sandwich",
            ingredients: ["chicken breast", "lettuce", "tomatoes", "red onions", "mayo"],
            price: 15.99,
            picture: "🍔",
            vegetarian: false,
        },
        {
            uuid: 2,
            name: "Garlic Mushroom Burger",
            ingredients: ["garlic", "mushrooms", "lettuce", "tomato", "onions"],
            price: 19.99,
            picture: "🍔",
            vegetarian: true,
        },
    ],
    beer: [
        {
            uuid: 0,
            name: "Brown Ale",
            ingredients: ["solstice mild", "dark shocolate", "pale cholate", "brown malt"],
            price: 14.99,
            picture: "🍺",
            nonAlcoholic: false,
        },
        {
            uuid: 1,
            name: "Crafted Lager",
            ingredients: ["solstice pilsner", "solstice flaked corn", "dextrapils"],
            price: 13.99,
            picture: "🍺",
            nonAlcoholic: false,
        },
        {
            uuid: 2,
            name: "Solo Pilsner",
            ingredients: ["malted barley", "wheat", "hops", "yeast", "water"],
            price: 15.99,
            picture: "🍺",
            nonAlcoholic: true,
        },
    ],
};